### PR TITLE
feat: support convert milliseconds and fix timezone

### LINKED ISSUE #35: 能不能把单位换算的功能也加进去
比如时间换算，可以把100000ms 换算成几天几时几分几秒。
还有大小单位等等其他的换算

### PR DESCRIPTION
**Pull request by abu-sufyan1**
close https://github.com/node-modules/utility/issues/35 https://github.com/node-modules/utility/issues/36

A function is added that takes milliseconds as an argument and returns Date object, if second optional parmeters is provided, it will return the date in the specified format.

Also, the pull request contains a fix other two test cases which were failing earlier.

We put the TIMEZONE object inside the resetTimezone() function, and now we are getting the timezone based on the date that needs to be transformed.

## Summary by CodeRabbit

- **New Features**
	- Added a utility function to convert milliseconds to formatted date strings.
	- Introduced new date formatting options with support for multiple time representations.
	- Enhanced timezone offset calculation for more precise date handling.
	- Added a function to convert `Date` objects to Unix timestamps.

- **Documentation**
	- Updated README with examples of the new date conversion function.

- **Tests**
	- Added comprehensive test cases for new date utility functions.
	- Improved test assertions for date-related methods.
	- Introduced a new test suite for validating date conversions and formats.

- **Chores**
	- Added a new dependency for improved caching functionality.

### CODE REVIEW

File: src/date.ts [hunk 1]
```diff
@@ -1,19 +1,14 @@
...
-  let _hourOffset = Math.floor(-(new Date().getTimezoneOffset()) / 60);
-  if (_hourOffset >= 0) {
-    TIMEZONE += '+';
-  } else {
-    TIMEZONE += '-';
-  }
-  _hourOffset = Math.abs(_hourOffset);
-  const _hourOffsetStr = _hourOffset < 10 ? `0${_hourOffset}` : `${_hourOffset}`;
-  TIMEZONE += `${_hourOffsetStr}00`;
+export function resetTimezone(date: Date) {
```
Comment (fengmk2) [inline src/date.ts:1]: We need to add a caching logic to minimize timezone calculations. We can cache the timezone calculation once per week or day. The cache should be implemented using ylru https://github.com/node-modules/ylru

Comment (abu-sufyan1) [reply src/date.ts:4]: added LRU logic.

File: package.json [hunk 2]
```diff
@@ -33,7 +33,8 @@
     "tsd": "^0.28.1",
     "tshy": "^3.0.2",
     "tshy-after": "^1.0.0",
-    "typescript": "^5.2.2"
+    "typescript": "^5.2.2",
+    "ylru": "^2.0.0"
```
[the remark this answers is not in the document]
Comment (fengmk2) [reply package.json:37]: @abu-sufyan1 need to fix it

File: src/date.ts [hunk 3]
```diff
@@ -1,19 +1,17 @@
...
-  if (_hourOffset >= 0) {
-    TIMEZONE += '+';
-  } else {
-    TIMEZONE += '-';
-  }
-  _hourOffset = Math.abs(_hourOffset);
-  const _hourOffsetStr = _hourOffset < 10 ? `0${_hourOffset}` : `${_hourOffset}`;
-  TIMEZONE += `${_hourOffsetStr}00`;
+import { LRU } from 'ylru';
+const lru = new LRU(0);
```
[the remark this answers is not in the document]
Comment (fengmk2) [reply src/date.ts:2]: same here

File: src/date.ts [hunk 4]
```diff
@@ -61,9 +59,18 @@ export function accessLogDate(d?: Date): string {
...
 }
 
+export function getTimezone(d: Date) {
+  const timeZone = lru.get('TIMEZONE');
+  if (timeZone === undefined) {
+    lru.set('TIMEZONE', resetTimezone(d), { maxAge: 8640000 });
+    return lru.get('TIMEZONE');
+  }
+  return timeZone;
+}
```
[the remark this answers is not in the document]
Comment (fengmk2) [reply src/date.ts:73]: @abu-sufyan1 should follow this suggestion

File: src/date.ts [hunk 5]
```diff
@@ -186,3 +194,41 @@ export function timestamp(t?: number | string): number | Date {
...
+/**
+ * Convert Date object to Unix timestamp in seconds.
+ */
+export function dateToUnixTimestamp(date: Date): number {
+  return Math.round(date.getTime() / 1000);
+}
+
+// use `as const` instead of enum
+// https://www.totaltypescript.com/books/total-typescript-essentials/deriving-types#using-as-const-for-javascript-style-enums
+export const DateFormat {
```
Comment (fengmk2) [inline src/date.ts:207]: I change enums here.

**Review by fengmk2 — APPROVED** [review]

**Review by fengmk2 — APPROVED** [review]

File: src/date.ts [hunk 6]
```diff
@@ -186,3 +194,39 @@ export function timestamp(t?: number | string): number | Date {
...
+
+/**
+ * Convert Date object to Unix timestamp in seconds.
+ */
+export function dateToUnixTimestamp(date: Date): number {
+  return Math.round(date.getTime() / 1000);
+}
+
+export enum DateFormat {
+  DateTimeWithTimeZone = 'DateTimeWithTimeZone',
```
Comment (fengmk2) [inline src/date.ts:206]: Change enum value to string is better than number.

**Comment by fengmk2** [comment]
@abu-sufyan1 Thanks for your open-source contributions 🎉
